# Site settings
title: "[ TERMINAL CONSOLE ]"
email: cyberspace@matrix.net
description: >-
  A retro hacker blog transmitting knowledge through the digital void.
  Lo-fi aesthetics, hi-fi content. Est. 2025.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
twitter_username: your_username
github_username:  your_username

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Permalink structure
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"
