# Site settings
title: "[ Nicolab ]"
email: nah
description: >-
  Just babbling on the internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicolab.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
twitter_username: null
github_username:  nlabrad

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Permalink structure
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"
